-- =============================================================================
-- STACKUP ENGINEERING ACADEMY
-- TASK 1.2 — DIMENSIONAL DATA MODEL
--
-- Database Engine: DuckDB
--
-- Warehouse Model:
--   dim_project
--   dim_employee           -- SCD Type 2
--   dim_vendor
--   dim_date
--   dim_employee_project   -- many-to-many bridge
--   fact_transactions
--
-- Sources:
--   outputs/projects_clean.csv
--   datasets/employees.csv
--   datasets/employees_salary_history.csv
--   outputs/transactions_clean.csv
--
-- DESIGN PRINCIPLES
-- -----------------------------------------------------------------------------
-- 1. All dimensions use integer surrogate keys.
-- 2. Source IDs are preserved as natural/business keys.
-- 3. Employee salary, role and level are handled using SCD Type 2.
-- 4. Multiple employee changes on the same day are collapsed to the final
--    state for that day because transactions contain DATE, not timestamp.
-- 5. Invalid hire dates are converted to NULL.
-- 6. Missing transaction amounts remain NULL; they are not converted to zero.
-- 7. Missing transaction approvers remain NULL.
-- 8. Transactions with valid employee IDs but dates preceding the employee's
--    first SCD record are retained and explicitly flagged.
-- 9. Vendor category is stored in the fact because one vendor can transact
--    under multiple categories.
-- =============================================================================


-- =============================================================================
-- CLEAN EXISTING WAREHOUSE TABLES
-- =============================================================================

DROP TABLE IF EXISTS fact_transactions;
DROP TABLE IF EXISTS dim_employee_project;
DROP TABLE IF EXISTS dim_date;
DROP TABLE IF EXISTS dim_vendor;
DROP TABLE IF EXISTS dim_employee;
DROP TABLE IF EXISTS dim_project;


-- =============================================================================
-- STAGING — PROJECTS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Cleaned projects generated by Task 1.1.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TEMP VIEW stg_projects AS

SELECT

    CAST(project_id AS VARCHAR)
        AS project_id,

    CAST(project_name AS VARCHAR)
        AS project_name,

    CAST(department AS VARCHAR)
        AS department,

    CAST(status AS VARCHAR)
        AS status,

    TRY_CAST(start_date AS DATE)
        AS start_date,

    TRY_CAST(end_date AS DATE)
        AS end_date,

    TRY_CAST(budget AS DOUBLE)
        AS budget,

    TRY_CAST(actual_cost AS DOUBLE)
        AS actual_cost,

    CAST(project_manager_id AS VARCHAR)
        AS project_manager_id,

    CAST(priority AS VARCHAR)
        AS priority,

    CAST(region AS VARCHAR)
        AS region,

    TRY_CAST(budget_variance AS DOUBLE)
        AS budget_variance,

    TRY_CAST(is_over_budget AS BOOLEAN)
        AS is_over_budget,

    TRY_CAST(duration_days AS INTEGER)
        AS duration_days,

    TRY_CAST(
        budget_utilisation_pct AS DOUBLE
    ) AS budget_utilisation_pct,

    CAST(status_category AS VARCHAR)
        AS status_category,

    CAST(risk_level AS VARCHAR)
        AS risk_level

FROM read_csv_auto(
    'outputs/projects_clean.csv',
    header = true
);


-- =============================================================================
-- STAGING — EMPLOYEES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Employee master data.
--
-- Invalid hire dates found during source profiling include:
--
--   -999
--   99999-01-01
--
-- DuckDB can represent unusually large years, therefore TRY_CAST alone is not
-- sufficient. An explicit YYYY-MM-DD validation and reasonable date range are
-- applied.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TEMP VIEW stg_employees AS

SELECT

    CAST(employee_id AS VARCHAR)
        AS employee_id,

    CAST(full_name AS VARCHAR)
        AS full_name,

    CAST(email AS VARCHAR)
        AS email,

    CAST(department AS VARCHAR)
        AS department,

    CAST(role AS VARCHAR)
        AS role,

    CAST(level AS VARCHAR)
        AS level,

    CASE

        WHEN hire_date IS NULL
            THEN NULL

        WHEN NOT REGEXP_MATCHES(
            TRIM(CAST(hire_date AS VARCHAR)),
            '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
        )
            THEN NULL

        WHEN TRY_CAST(hire_date AS DATE) IS NULL
            THEN NULL

        WHEN TRY_CAST(hire_date AS DATE)
             < DATE '1950-01-01'
            THEN NULL

        WHEN TRY_CAST(hire_date AS DATE)
             > CURRENT_DATE
            THEN NULL

        ELSE TRY_CAST(
            hire_date AS DATE
        )

    END AS hire_date,

    TRY_CAST(salary AS DOUBLE)
        AS salary,

    CAST(manager_id AS VARCHAR)
        AS manager_id,

    CAST(region AS VARCHAR)
        AS region,

    CAST(status AS VARCHAR)
        AS status,

    TRY_CAST(
        years_experience AS INTEGER
    ) AS years_experience

FROM read_csv_auto(
    'datasets/employees.csv',
    header = true
);


-- =============================================================================
-- STAGING — EMPLOYEE SALARY HISTORY
-- =============================================================================

CREATE OR REPLACE TEMP VIEW stg_employee_salary_history AS

SELECT

    CAST(employee_id AS VARCHAR)
        AS employee_id,

    TRY_CAST(previous_salary AS DOUBLE)
        AS previous_salary,

    TRY_CAST(new_salary AS DOUBLE)
        AS new_salary,

    CAST(previous_role AS VARCHAR)
        AS previous_role,

    CAST(new_role AS VARCHAR)
        AS new_role,

    CAST(previous_level AS VARCHAR)
        AS previous_level,

    CAST(new_level AS VARCHAR)
        AS new_level,

    TRY_CAST(effective_date AS DATE)
        AS effective_date,

    CAST(change_type AS VARCHAR)
        AS change_type,

    CAST(change_reason AS VARCHAR)
        AS change_reason

FROM read_csv_auto(
    'datasets/employees_salary_history.csv',
    header = true
);


-- =============================================================================
-- STAGING — TRANSACTIONS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Cleaned transactions generated by the Python ETL pipeline.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TEMP VIEW stg_transactions AS

SELECT *

FROM read_csv_auto(
    'outputs/transactions_clean.csv',
    header = true,
    nullstr = ''
);


-- =============================================================================
-- DIMENSION: PROJECT
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Grain:
-- One row per project.
--
-- project_key:
-- Warehouse surrogate key.
--
-- project_id:
-- Source-system natural key.
-- -----------------------------------------------------------------------------

CREATE TABLE dim_project
(
    project_key INTEGER PRIMARY KEY,

    project_id VARCHAR NOT NULL UNIQUE,

    project_name VARCHAR,

    department VARCHAR,

    status VARCHAR,

    start_date DATE,

    end_date DATE,

    budget DOUBLE,

    actual_cost DOUBLE,

    project_manager_id VARCHAR,

    priority VARCHAR,

    region VARCHAR,

    budget_variance DOUBLE,

    is_over_budget BOOLEAN,

    duration_days INTEGER,

    budget_utilisation_pct DOUBLE,

    status_category VARCHAR,

    risk_level VARCHAR
);


INSERT INTO dim_project

SELECT

    CAST(
        ROW_NUMBER() OVER
        (
            ORDER BY project_id
        )
        AS INTEGER
    ) AS project_key,

    project_id,

    project_name,

    department,

    status,

    start_date,

    end_date,

    budget,

    actual_cost,

    project_manager_id,

    priority,

    region,

    budget_variance,

    is_over_budget,

    duration_days,

    budget_utilisation_pct,

    status_category,

    risk_level

FROM stg_projects;


-- =============================================================================
-- DIMENSION: EMPLOYEE — SCD TYPE 2
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Grain:
-- One row per employee version.
--
-- Historical SCD attributes:
--   salary
--   role
--   level
--
-- Source salary-history rows describe changes in those attributes.
--
-- Static/current attributes such as:
--   full_name
--   email
--   department
--   manager_id
--   region
--   status
--
-- are not historically tracked by the salary history source, so the current
-- employee-master values are copied across SCD versions.
--
-- Same-day history:
-- EMP0084 contains two employee changes on 2025-03-02.
--
-- Since transaction_date contains only a DATE and has no timestamp, two states
-- occurring within the same calendar day cannot be differentiated reliably.
-- The final state for that date is therefore retained in dim_employee.
-- -----------------------------------------------------------------------------

CREATE TABLE dim_employee
(
    employee_key INTEGER PRIMARY KEY,

    employee_id VARCHAR NOT NULL,

    full_name VARCHAR,

    email VARCHAR,

    department VARCHAR,

    role VARCHAR,

    level VARCHAR,

    hire_date DATE,

    salary DOUBLE,

    manager_id VARCHAR,

    region VARCHAR,

    status VARCHAR,

    years_experience INTEGER,

    valid_from DATE NOT NULL,

    valid_to DATE NOT NULL,

    is_current BOOLEAN NOT NULL,

    change_type VARCHAR,

    change_reason VARCHAR
);


INSERT INTO dim_employee

WITH history_ranked AS
(
    SELECT

        h.*,

        ROW_NUMBER() OVER
        (
            PARTITION BY
                h.employee_id,
                h.effective_date

            ORDER BY

                CASE h.change_type

                    WHEN 'Hire'
                        THEN 1

                    WHEN 'Annual Raise'
                        THEN 2

                    WHEN 'Promotion'
                        THEN 3

                    ELSE 4

                END,

                h.new_salary,

                h.new_role,

                h.new_level

        ) AS same_day_sequence,

        COUNT(*) OVER
        (
            PARTITION BY
                h.employee_id,
                h.effective_date
        ) AS same_day_count

    FROM stg_employee_salary_history h
),


-- -----------------------------------------------------------------------------
-- Retain the final employee state for each employee/date combination.
-- -----------------------------------------------------------------------------

history_daily_final AS
(
    SELECT *

    FROM history_ranked

    WHERE same_day_sequence
          = same_day_count
),


-- -----------------------------------------------------------------------------
-- Obtain next effective date for each employee version.
-- -----------------------------------------------------------------------------

history_with_next_date AS
(
    SELECT

        employee_id,

        new_salary,

        new_role,

        new_level,

        effective_date,

        change_type,

        change_reason,

        LEAD(effective_date) OVER
        (
            PARTITION BY employee_id
            ORDER BY effective_date
        ) AS next_effective_date,

        ROW_NUMBER() OVER
        (
            PARTITION BY employee_id
            ORDER BY effective_date
        ) AS employee_version_number

    FROM history_daily_final
),


-- -----------------------------------------------------------------------------
-- Build SCD versions for employees with history.
-- -----------------------------------------------------------------------------

history_versions AS
(
    SELECT

        e.employee_id,

        e.full_name,

        e.email,

        e.department,

        h.new_role
            AS role,

        h.new_level
            AS level,

        e.hire_date,

        h.new_salary
            AS salary,

        e.manager_id,

        e.region,

        e.status,

        e.years_experience,

        h.effective_date
            AS valid_from,

        CASE

            WHEN h.next_effective_date
                 IS NULL

                THEN DATE '9999-12-31'

            ELSE CAST(
                h.next_effective_date
                - INTERVAL 1 DAY
                AS DATE
            )

        END AS valid_to,

        CASE

            WHEN h.next_effective_date
                 IS NULL

                THEN TRUE

            ELSE FALSE

        END AS is_current,

        h.change_type,

        h.change_reason

    FROM history_with_next_date h

    INNER JOIN stg_employees e

        ON h.employee_id
           = e.employee_id
),


-- -----------------------------------------------------------------------------
-- Employees without salary history receive one current dimension record.
--
-- Invalid/missing hire dates use 1900-01-01 as the technical warehouse lower
-- bound. The original hire_date remains NULL in the descriptive hire_date
-- column.
-- -----------------------------------------------------------------------------

employees_without_history AS
(
    SELECT

        e.employee_id,

        e.full_name,

        e.email,

        e.department,

        e.role,

        e.level,

        e.hire_date,

        e.salary,

        e.manager_id,

        e.region,

        e.status,

        e.years_experience,

        COALESCE(
            e.hire_date,
            DATE '1900-01-01'
        ) AS valid_from,

        DATE '9999-12-31'
            AS valid_to,

        TRUE
            AS is_current,

        'Current Record'
            AS change_type,

        'No salary history available'
            AS change_reason

    FROM stg_employees e

    WHERE NOT EXISTS
    (
        SELECT 1

        FROM stg_employee_salary_history h

        WHERE h.employee_id
              = e.employee_id
    )
),


-- -----------------------------------------------------------------------------
-- Combine historical and no-history employee records.
-- -----------------------------------------------------------------------------

all_employee_versions AS
(
    SELECT *

    FROM history_versions


    UNION ALL


    SELECT *

    FROM employees_without_history
)


SELECT

    CAST(
        ROW_NUMBER() OVER
        (
            ORDER BY

                employee_id,

                valid_from,

                salary
        )
        AS INTEGER
    ) AS employee_key,

    employee_id,

    full_name,

    email,

    department,

    role,

    level,

    hire_date,

    salary,

    manager_id,

    region,

    status,

    years_experience,

    valid_from,

    valid_to,

    is_current,

    change_type,

    change_reason

FROM all_employee_versions;


-- =============================================================================
-- DIMENSION: VENDOR
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Grain:
-- One row per vendor.
--
-- Source inspection confirmed:
--   25 vendor IDs
--   25 vendor names
--   no vendor_id -> multiple vendor_name conflicts
--
-- Transaction category is NOT stored here because the same vendor can appear
-- under multiple categories.
-- -----------------------------------------------------------------------------

CREATE TABLE dim_vendor
(
    vendor_key INTEGER PRIMARY KEY,

    vendor_id VARCHAR NOT NULL UNIQUE,

    vendor_name VARCHAR
);


INSERT INTO dim_vendor

SELECT

    CAST(
        ROW_NUMBER() OVER
        (
            ORDER BY vendor_id
        )
        AS INTEGER
    ) AS vendor_key,

    vendor_id,

    vendor_name

FROM
(
    SELECT DISTINCT

        CAST(vendor_id AS VARCHAR)
            AS vendor_id,

        CAST(vendor_name AS VARCHAR)
            AS vendor_name

    FROM stg_transactions

    WHERE vendor_id IS NOT NULL
);


-- =============================================================================
-- DIMENSION: DATE
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Grain:
-- One row per calendar date.
--
-- Transaction source date range observed:
--   2022-01-06 to 2026-08-04
--
-- date_key:
-- Integer warehouse surrogate key.
--
-- full_date:
-- Natural calendar date.
-- -----------------------------------------------------------------------------

CREATE TABLE dim_date
(
    date_key INTEGER PRIMARY KEY,

    full_date DATE NOT NULL UNIQUE,

    year INTEGER,

    quarter INTEGER,

    month INTEGER,

    month_name VARCHAR,

    week INTEGER,

    day INTEGER,

    day_name VARCHAR,

    is_weekend BOOLEAN
);


INSERT INTO dim_date

WITH date_bounds AS
(
    SELECT

        MIN(
            TRY_CAST(
                transaction_date AS DATE
            )
        ) AS min_date,

        MAX(
            TRY_CAST(
                transaction_date AS DATE
            )
        ) AS max_date

    FROM stg_transactions
),

calendar AS
(
    SELECT

        CAST(
            generate_series AS DATE
        ) AS full_date

    FROM date_bounds,

    generate_series(
        min_date,
        max_date,
        INTERVAL 1 DAY
    )
)


SELECT

    CAST(
        ROW_NUMBER() OVER
        (
            ORDER BY full_date
        )
        AS INTEGER
    ) AS date_key,

    full_date,

    CAST(
        EXTRACT(
            YEAR FROM full_date
        )
        AS INTEGER
    ) AS year,

    CAST(
        EXTRACT(
            QUARTER FROM full_date
        )
        AS INTEGER
    ) AS quarter,

    CAST(
        EXTRACT(
            MONTH FROM full_date
        )
        AS INTEGER
    ) AS month,

    STRFTIME(
        full_date,
        '%B'
    ) AS month_name,

    CAST(
        EXTRACT(
            WEEK FROM full_date
        )
        AS INTEGER
    ) AS week,

    CAST(
        EXTRACT(
            DAY FROM full_date
        )
        AS INTEGER
    ) AS day,

    STRFTIME(
        full_date,
        '%A'
    ) AS day_name,

    CASE

        WHEN EXTRACT(
            ISODOW FROM full_date
        ) IN (6, 7)

            THEN TRUE

        ELSE FALSE

    END AS is_weekend

FROM calendar;


-- =============================================================================
-- BRIDGE: EMPLOYEE ↔ PROJECT
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Employee/project is many-to-many.
--
-- Observable relationships available in the source:
--
--   projects.project_manager_id
--       -> Project Manager
--
--   transactions.approved_by
--       -> Transaction Approver
--
-- The bridge resolves these relationships using the CURRENT employee dimension
-- row. Historical employee versions remain available through fact_transactions.
-- -----------------------------------------------------------------------------

CREATE TABLE dim_employee_project
(
    employee_project_key INTEGER PRIMARY KEY,

    employee_key INTEGER NOT NULL,

    project_key INTEGER NOT NULL,

    relationship_type VARCHAR NOT NULL,

    FOREIGN KEY (employee_key)
        REFERENCES dim_employee(employee_key),

    FOREIGN KEY (project_key)
        REFERENCES dim_project(project_key)
);


INSERT INTO dim_employee_project

WITH employee_project_relationships AS
(
    -- -------------------------------------------------------------------------
    -- Project manager relationship
    -- -------------------------------------------------------------------------

    SELECT DISTINCT

        CAST(
            project_manager_id AS VARCHAR
        ) AS employee_id,

        CAST(
            project_id AS VARCHAR
        ) AS project_id,

        'Project Manager'
            AS relationship_type

    FROM stg_projects

    WHERE project_manager_id
          IS NOT NULL


    UNION


    -- -------------------------------------------------------------------------
    -- Transaction approver relationship
    -- -------------------------------------------------------------------------

    SELECT DISTINCT

        CAST(
            approved_by AS VARCHAR
        ) AS employee_id,

        CAST(
            project_id AS VARCHAR
        ) AS project_id,

        'Transaction Approver'
            AS relationship_type

    FROM stg_transactions

    WHERE approved_by IS NOT NULL

      AND TRIM(
            CAST(
                approved_by AS VARCHAR
            )
          ) <> ''
),

resolved_relationships AS
(
    SELECT

        e.employee_key,

        p.project_key,

        r.relationship_type

    FROM employee_project_relationships r

    INNER JOIN dim_employee e

        ON r.employee_id
           = e.employee_id

       AND e.is_current
           = TRUE

    INNER JOIN dim_project p

        ON r.project_id
           = p.project_id
)


SELECT

    CAST(
        ROW_NUMBER() OVER
        (
            ORDER BY

                employee_key,

                project_key,

                relationship_type
        )
        AS INTEGER
    ) AS employee_project_key,

    employee_key,

    project_key,

    relationship_type

FROM resolved_relationships;


-- =============================================================================
-- FACT TABLE: TRANSACTIONS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Grain:
-- One row per source transaction.
--
-- Expected source rows:
--   50,000
--
-- Foreign keys:
--
--   project_key
--       -> dim_project
--
--   employee_key
--       -> dim_employee
--
--   vendor_key
--       -> dim_vendor
--
--   date_key
--       -> dim_date
--
--
-- EMPLOYEE SCD RESOLUTION
-- -----------------------------------------------------------------------------
-- Preferred employee_key:
-- Employee version whose valid date range contains transaction_date.
--
-- Source profiling identified 219 transactions where:
--
--   approved_by is valid
--   BUT transaction_date is earlier than that employee's first SCD version.
--
-- These rows are retained by resolving them to the employee's FIRST known SCD
-- version and setting employee_scd_date_mismatch_flag = TRUE.
--
-- This avoids:
--   - losing transactions
--   - fabricating an employee ID
--   - silently changing historical SCD dates
--
-- Missing approved_by remains NULL.
-- -----------------------------------------------------------------------------

CREATE TABLE fact_transactions
(
    transaction_key BIGINT PRIMARY KEY,

    transaction_id VARCHAR NOT NULL UNIQUE,

    project_key INTEGER NOT NULL,

    employee_key INTEGER,

    vendor_key INTEGER NOT NULL,

    date_key INTEGER NOT NULL,

    category VARCHAR,

    amount DOUBLE,

    currency VARCHAR,

    payment_status VARCHAR,

    invoice_ref VARCHAR,

    notes VARCHAR,

    amount_missing_flag BOOLEAN,

    approver_missing_flag BOOLEAN,

    paid_without_approver_flag BOOLEAN,

    disputed_amount_missing_flag BOOLEAN,

    notes_missing_flag BOOLEAN,

    employee_scd_date_mismatch_flag BOOLEAN,

    dq_issue_flag BOOLEAN,

    FOREIGN KEY (project_key)
        REFERENCES dim_project(project_key),

    FOREIGN KEY (employee_key)
        REFERENCES dim_employee(employee_key),

    FOREIGN KEY (vendor_key)
        REFERENCES dim_vendor(vendor_key),

    FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key)
);


INSERT INTO fact_transactions

WITH transaction_base AS
(
    SELECT

        t.*,

        TRY_CAST(
            t.transaction_date AS DATE
        ) AS transaction_date_parsed

    FROM stg_transactions t
),


-- -----------------------------------------------------------------------------
-- Exact SCD match.
-- -----------------------------------------------------------------------------

exact_employee_match AS
(
    SELECT

        t.transaction_id,

        e.employee_key

    FROM transaction_base t

    INNER JOIN dim_employee e

        ON CAST(
            t.approved_by AS VARCHAR
        ) = e.employee_id

       AND t.transaction_date_parsed
           BETWEEN e.valid_from
               AND e.valid_to
),


-- -----------------------------------------------------------------------------
-- First known SCD record for each employee.
--
-- Used only as a fallback for valid employee IDs where transaction_date occurs
-- before the first known employee version.
-- -----------------------------------------------------------------------------

first_employee_version AS
(
    SELECT

        employee_id,

        employee_key,

        valid_from,

        ROW_NUMBER() OVER
        (
            PARTITION BY employee_id

            ORDER BY
                valid_from,
                employee_key
        ) AS rn

    FROM dim_employee
),


resolved_transactions AS
(
    SELECT

        t.*,

        exact.employee_key
            AS exact_employee_key,

        first_version.employee_key
            AS fallback_employee_key,

        CASE

            WHEN t.approved_by IS NULL
                THEN FALSE

            WHEN TRIM(
                CAST(
                    t.approved_by AS VARCHAR
                )
            ) = ''
                THEN FALSE

            WHEN exact.employee_key
                 IS NOT NULL
                THEN FALSE

            WHEN first_version.employee_key
                 IS NOT NULL
                THEN TRUE

            ELSE FALSE

        END AS employee_scd_date_mismatch_flag

    FROM transaction_base t

    LEFT JOIN exact_employee_match exact

        ON CAST(
            t.transaction_id AS VARCHAR
        ) = exact.transaction_id

    LEFT JOIN first_employee_version first_version

        ON CAST(
            t.approved_by AS VARCHAR
        ) = first_version.employee_id

       AND first_version.rn = 1
)


SELECT

    CAST(
        ROW_NUMBER() OVER
        (
            ORDER BY transaction_id
        )
        AS BIGINT
    ) AS transaction_key,

    CAST(
        transaction_id AS VARCHAR
    ) AS transaction_id,

    p.project_key,

    CASE

        WHEN exact_employee_key IS NOT NULL
            THEN exact_employee_key

        WHEN approver_missing_flag
            THEN NULL

        ELSE fallback_employee_key

    END AS employee_key,

    v.vendor_key,

    d.date_key,

    CAST(
        category AS VARCHAR
    ) AS category,

    TRY_CAST(
        amount AS DOUBLE
    ) AS amount,

    CAST(
        currency AS VARCHAR
    ) AS currency,

    CAST(
        payment_status AS VARCHAR
    ) AS payment_status,

    CAST(
        invoice_ref AS VARCHAR
    ) AS invoice_ref,

    CAST(
        notes AS VARCHAR
    ) AS notes,

    COALESCE(
        TRY_CAST(
            amount_missing_flag
            AS BOOLEAN
        ),
        FALSE
    ) AS amount_missing_flag,

    COALESCE(
        TRY_CAST(
            approver_missing_flag
            AS BOOLEAN
        ),
        FALSE
    ) AS approver_missing_flag,

    COALESCE(
        TRY_CAST(
            paid_without_approver_flag
            AS BOOLEAN
        ),
        FALSE
    ) AS paid_without_approver_flag,

    COALESCE(
        TRY_CAST(
            disputed_amount_missing_flag
            AS BOOLEAN
        ),
        FALSE
    ) AS disputed_amount_missing_flag,

    COALESCE(
        TRY_CAST(
            notes_missing_flag
            AS BOOLEAN
        ),
        FALSE
    ) AS notes_missing_flag,

    employee_scd_date_mismatch_flag,

    (
        COALESCE(
            TRY_CAST(
                dq_issue_flag AS BOOLEAN
            ),
            FALSE
        )

        OR employee_scd_date_mismatch_flag
    ) AS dq_issue_flag

FROM resolved_transactions t

INNER JOIN dim_project p

    ON CAST(
        t.project_id AS VARCHAR
    ) = p.project_id

INNER JOIN dim_vendor v

    ON CAST(
        t.vendor_id AS VARCHAR
    ) = v.vendor_id

INNER JOIN dim_date d

    ON t.transaction_date_parsed
       = d.full_date
;


-- =============================================================================
-- VALIDATION 1 — WAREHOUSE TABLE COUNTS
-- =============================================================================

SELECT

    'dim_project'
        AS table_name,

    COUNT(*)
        AS row_count

FROM dim_project


UNION ALL


SELECT

    'dim_employee',

    COUNT(*)

FROM dim_employee


UNION ALL


SELECT

    'dim_vendor',

    COUNT(*)

FROM dim_vendor


UNION ALL


SELECT

    'dim_date',

    COUNT(*)

FROM dim_date


UNION ALL


SELECT

    'dim_employee_project',

    COUNT(*)

FROM dim_employee_project


UNION ALL


SELECT

    'fact_transactions',

    COUNT(*)

FROM fact_transactions
;


-- =============================================================================
-- VALIDATION 2 — EMPLOYEE SCD SUMMARY
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Because one same-day duplicate employee state is collapsed:
--
-- Expected dim_employee total:
--   2231
--
-- Expected distinct employees:
--   1000
--
-- Expected current versions:
--   1000
--
-- Expected historical versions:
--   1231
-- -----------------------------------------------------------------------------

SELECT

    COUNT(*)
        AS total_versions,

    COUNT(
        DISTINCT employee_id
    ) AS employees,

    SUM(
        CASE

            WHEN is_current
                THEN 1

            ELSE 0

        END
    ) AS current_versions,

    SUM(
        CASE

            WHEN NOT is_current
                THEN 1

            ELSE 0

        END
    ) AS historical_versions

FROM dim_employee
;


-- =============================================================================
-- VALIDATION 3 — EXACTLY ONE CURRENT VERSION PER EMPLOYEE
-- =============================================================================

-- Expected:
-- zero rows

SELECT

    employee_id,

    COUNT(*)
        AS current_count

FROM dim_employee

WHERE is_current = TRUE

GROUP BY employee_id

HAVING COUNT(*) <> 1
;


-- =============================================================================
-- VALIDATION 4 — INVALID SCD DATE RANGES
-- =============================================================================

-- Expected:
-- zero rows

SELECT

    employee_id,

    employee_key,

    valid_from,

    valid_to,

    role,

    level,

    salary

FROM dim_employee

WHERE valid_to
      < valid_from

ORDER BY

    employee_id,

    valid_from
;


-- =============================================================================
-- VALIDATION 5 — OVERLAPPING SCD DATE RANGES
-- =============================================================================

-- Expected:
-- zero rows

SELECT

    a.employee_id,

    a.employee_key
        AS employee_key_1,

    a.valid_from
        AS valid_from_1,

    a.valid_to
        AS valid_to_1,

    b.employee_key
        AS employee_key_2,

    b.valid_from
        AS valid_from_2,

    b.valid_to
        AS valid_to_2

FROM dim_employee a

INNER JOIN dim_employee b

    ON a.employee_id
       = b.employee_id

   AND a.employee_key
       < b.employee_key

   AND a.valid_from
       <= b.valid_to

   AND b.valid_from
       <= a.valid_to

ORDER BY a.employee_id
;


-- =============================================================================
-- VALIDATION 6 — CURRENT EMPLOYEE STATE VS SOURCE MASTER
-- =============================================================================

-- Expected:
-- zero rows

SELECT

    d.employee_id,

    d.salary
        AS dimension_salary,

    e.salary
        AS source_salary,

    d.role
        AS dimension_role,

    e.role
        AS source_role,

    d.level
        AS dimension_level,

    e.level
        AS source_level

FROM dim_employee d

INNER JOIN stg_employees e

    ON d.employee_id
       = e.employee_id

WHERE d.is_current
      = TRUE

  AND
  (
        d.salary
        <> e.salary

        OR COALESCE(
            d.role,
            ''
        )
        <> COALESCE(
            e.role,
            ''
        )

        OR COALESCE(
            d.level,
            ''
        )
        <> COALESCE(
            e.level,
            ''
        )
  )
;


-- =============================================================================
-- VALIDATION 7 — FACT TABLE
-- =============================================================================

-- Expected:
--
-- fact_rows                = 50000
-- distinct_transactions    = 50000
-- missing_project_key      = 0
-- missing_vendor_key       = 0
-- missing_date_key         = 0
-- null_employee_key        = 2444
--
-- 2444 is expected because those source transactions genuinely have no
-- approved_by value.
-- -----------------------------------------------------------------------------

SELECT

    COUNT(*)
        AS fact_rows,

    COUNT(
        DISTINCT transaction_id
    ) AS distinct_transactions,

    SUM(
        CASE

            WHEN project_key IS NULL
                THEN 1

            ELSE 0

        END
    ) AS missing_project_key,

    SUM(
        CASE

            WHEN vendor_key IS NULL
                THEN 1

            ELSE 0

        END
    ) AS missing_vendor_key,

    SUM(
        CASE

            WHEN date_key IS NULL
                THEN 1

            ELSE 0

        END
    ) AS missing_date_key,

    SUM(
        CASE

            WHEN employee_key IS NULL
                THEN 1

            ELSE 0

        END
    ) AS null_employee_key

FROM fact_transactions
;


-- =============================================================================
-- VALIDATION 8 — EMPLOYEE SCD DATE MISMATCHES
-- =============================================================================

-- Expected:
-- approximately / exactly 219 based on source profiling.

SELECT

    COUNT(*)
        AS employee_scd_date_mismatch_count

FROM fact_transactions

WHERE employee_scd_date_mismatch_flag
      = TRUE
;


-- =============================================================================
-- VALIDATION 9 — TRANSACTION DQ RECONCILIATION
-- =============================================================================

-- Expected:
--
-- missing_amount               = 740
-- paid_without_approver        = 1827
-- missing_disputed_amount      = 740
-- -----------------------------------------------------------------------------

SELECT

    SUM(
        CASE

            WHEN amount IS NULL
                THEN 1

            ELSE 0

        END
    ) AS missing_amount,

    SUM(
        CASE

            WHEN paid_without_approver_flag
                THEN 1

            ELSE 0

        END
    ) AS paid_without_approver,

    SUM(
        CASE

            WHEN disputed_amount_missing_flag
                THEN 1

            ELSE 0

        END
    ) AS missing_disputed_amount

FROM fact_transactions
;


-- =============================================================================
-- VALIDATION 10 — MISSING AMOUNT BY PAYMENT STATUS
-- =============================================================================

SELECT

    payment_status,

    COUNT(*)
        AS total_transactions,

    SUM(
        CASE

            WHEN amount IS NULL
                THEN 1

            ELSE 0

        END
    ) AS missing_amount_count

FROM fact_transactions

GROUP BY payment_status

ORDER BY payment_status
;


-- =============================================================================
-- VALIDATION 11 — SAMPLE STAR SCHEMA QUERY
-- =============================================================================

SELECT

    f.transaction_id,

    d.full_date
        AS transaction_date,

    p.project_id,

    p.project_name,

    e.employee_id
        AS approved_by,

    e.full_name
        AS approver_name,

    v.vendor_id,

    v.vendor_name,

    f.category,

    f.amount,

    f.currency,

    f.payment_status,

    f.employee_scd_date_mismatch_flag,

    f.dq_issue_flag

FROM fact_transactions f

INNER JOIN dim_project p

    ON f.project_key
       = p.project_key

INNER JOIN dim_vendor v

    ON f.vendor_key
       = v.vendor_key

INNER JOIN dim_date d

    ON f.date_key
       = d.date_key

LEFT JOIN dim_employee e

    ON f.employee_key
       = e.employee_key

ORDER BY

    d.full_date,

    f.transaction_id

LIMIT 20;